# Generated by Django 4.2.2 on 2023-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=210)),
                ('image', models.ImageField(upload_to='off_img/')),
            ],
        ),
    ]
