# Generated by Django 4.2.2 on 2023-07-25 02:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='off_img/')),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
