# Generated by Django 4.2.2 on 2023-08-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Register1',
        ),
    ]
